language: minimal

services:
  - docker

script:
  - docker version
  - docker build -t yesenarman/simple-node .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
  - docker push yesenarman/simple-node
