apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-node
        image: yesenarman/udacity-simple-node
        ports:
        - containerPort: 80
        env:
          - name: FAVORITE_FOOD
            value: "Hamburger"
